# Use root/example as user/password credentials
version: "3.1"

services:
  backend:
    build: "./"
    image: formula-pil:latest
    container_name: api-formula
    hostname: apiformula
    command: sh -c "env | grep -E '^[A-Za-z_]+=' > .env && git checkout main && git pull && npm i && npm run build && cp -r ./templates /app/dist/templates && npm run start"
    volumes:
      - "./photo:/app/photo"
      - "./pdf:/app/pdf"
      - "./signature:/app/signature"
    ports:
      - target: 9334
        published: 9334
        protocol: tcp
    env_file:
      - ./.env
    restart: always